export enum Subjects {
  Todo = 'todo',
  Update = 'update',
  TodoCreated = 'todoCreated',
  TodoUpdated = 'todoUpdated',
  TodoDeleted = 'todoDeleted',
  CommentCreated = 'commentCreated',
  CommentDeleted = 'commentDeleted',
  // Comment_TodoCreated = 'comment-todoCreated',
  // Comment_TodoDeleted = 'comment-todoDeleted',
  // Query_TodoCreated = 'query-todoCreated',
  // Query_TodoUpdated = 'query-todoUpdated',
  // Query_TodoDeleted = 'query-todoDeleted',
  // Query_CommentCreated = 'query-commentCreated',
  // Query_CommentDeleted = 'query-commentDeleted',
}