apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: fan0223/query
          env:
            - name: MONGO_URI
              value: 'mongodb://query-mongo-srv:27017/query'
            - name: NODE_ENV
              value: 'development'
            - name: JWT_KEY
              value: 'jwtSecret'
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 3000
      targetPort: 3000
