name: test-todo

on:
  pull_request:
    paths:
      - 'todo/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd todo && npm install && npm run test:ci
